apiVersion: v1
kind: Service
metadata:
  name: headlamp-service
  namespace: kube-system
  labels:
    app: headlamp
spec:
  type: NodePort
  selector:
    app: headlamp
  ports:
    - port: 4466
      targetPort: 4466
      nodePort: 30080
      protocol: TCP
