apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  namespace: monitoring
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce

  # k3s includes local-path StorageClass by default.
  # Provisioning happens on the node where pod is scheduled (blacknode).
  storageClassName: local-path

  resources:
    requests:
      storage: 5Gi
